version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-buster
    parallelism: 1
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Configure Project
          command: cp config/default.yml.example config/default.yml
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
